apiVersion: v1
kind: Pod
metadata:
  name: playrepo-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: kosenkovps/play-repo:golang
    name: playrepo
    ports:
    - containerPort: 8080
      protocol: TCP 