apiVersion: v1
kind: ReplicationController
metadata:
  name: playrepo
spec:
  replicas: 3
  selector:
    app: playrepo
  template:
    metadata:
      labels:
        app: playrepo
    spec:
      containers:
      - name: playrepo
        image: kosenkovps/play-repo:latest
        ports:
        - containerPort: 8080