apiVersion: v1
kind: Pod
metadata:
  name: playrepo-gpu
spec:
  nodeSelector:
    gpu: "true"
  containers:
  - image: kosenkovps/play-repo:golang
    name: playrepo
    ports:
    - containerPort: 8080
      protocol: TCP 